# Generated by Django 5.0.7 on 2024-08-05 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_hashtag_publication_delete_danislan'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
