# Generated by Django 5.0.7 on 2024-08-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_publication_category_publication_hashtags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='create_at',
            field=models.DateField(null=True),
        ),
    ]
