# Generated by Django 5.0.7 on 2024-08-09 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_publication_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='hashtags',
            field=models.ManyToManyField(null=True, related_name='hashtags', to='blog.hashtag'),
        ),
        migrations.CreateModel(
            name='PublicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.publication')),
            ],
        ),
    ]
