# Generated by Django 5.0.7 on 2024-08-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_hashtag_title_alter_publication_hashtags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
