# Generated by Django 5.0.7 on 2024-08-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_clientcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationcomment',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
