# Generated by Django 5.0.7 on 2024-08-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_publication_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описания'),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описания'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
