# Generated by Django 5.0.7 on 2024-08-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_category_title_en_publication_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='title_en',
        ),
    ]
